version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexagonal-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: hexagonal_db
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: freelance-marketplace-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hexagonal_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
